version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=secure
        - MONGO_INITDB_DATABASE=admin
    ports:
        - 27017:27017
    volumes:
        - ./assets/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  web:
    build: .
    working_dir: /app
    environment:
      - PORT=9000
    depends_on:
      - "mongodb"
    ports:
      - "9000:9000"